<section class="section">
    <h2><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">[field:fulltitle/]</a></h2>
    <div class="left-thumbnail"> <a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank"><img src="[field:litpic/]" alt="[field:fulltitle/]"/></a> </div>
    <div class="intro">[field:description/]... </div>
    <div class="intro-meta"> <span>日期：[field:pubdate function='strftime("%Y-%m-%d %H:%M:%S",@me)'/]</span> <span>人气：[field:click/] </span> <span class="readmore"><a href="[field:arcurl/]" title="[field:fulltitle/]" target="_blank">阅读全文</a></span> </div>
    <div class="clear"></div>
  </section>