
<field:name itemname="昵称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:web itemname="网址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:web>

<field:comment itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:comment>



<field:liuyanshijian itemname="留言时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:liuyanshijian>
