<li id="comment-3">
            <div class="floor">[field:global.autoindex/]楼</div>
            <div class="gravatar"> <img src="/skin/images/liuyan.gif" alt="用户头像"/> </div>
            <div class="cmt-meta">
              <div class="user"> <a>[field:name/]</a> </div>
              <div class="time"> [field:timesj/] </div>
            </div>
            <div class="cmt-cont"> [field:comment/] </div>
          </li>