<?php
$z[0]=Array("arcurl","",44,59);
$z[0][4]=array();
$z[1]=Array("title","",68,82);
$z[1][4]=array();
$z[2]=Array("title","",100,114);
$z[2][4]=array();
$z[3]=Array("arcurl","",167,182);
$z[3][4]=array();
$z[4]=Array("title","",191,205);
$z[4][4]=array();
$z[5]=Array("litpic","",233,248);
$z[5][4]=array();
$z[6]=Array("title","",255,269);
$z[6][4]=array();
$z[7]=Array("description","",308,328);
$z[7][4]=array();
$z[8]=Array("pubdate","",384,445);
$z[8][4]=array();
$z[8][4]['function']="strftime(\"%Y-%m-%d %H:%M:%S\",@me)";
$z[9]=Array("click","",468,482);
$z[9][4]=array();
$z[10]=Array("arcurl","",523,538);
$z[10][4]=array();
$z[11]=Array("title","",547,561);
$z[11][4]=array();

?>