<?php
$z[0]=Array("global","",90,116);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",156,182);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n            <li class=\"common\"><a href=\"{dede:field.typeurl/}\">{dede:field.typename/}</a>\r\n              <ul class=\"sub-nav\">\r\n               {dede:channel type=\"son\"} \r\n                <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n               {/dede:channel}\r\n              </ul>\r\n            </li>\r\n		",469,846);
$z[2][4]=array();
$z[2][4]['typeid']="top";

?>