<?php
$z[0]=Array("field","",293,312);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",313,339);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",380,409);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",449,507);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1063,1098);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("php"," echo \$showtime=date('Y-m-d H:i:s');",2391,2448);
$z[5][4]=array();
$z[6]=Array("include","",3315,3351);
$z[6][4]=array();
$z[6][4]['filename']="right.htm";
$z[7]=Array("include","",3355,3392);
$z[7][4]=array();
$z[7][4]['filename']="footer.htm";

?>