<?php
$z[0]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></li>\r\n ",662,849);
$z[0][4]=array();
$z[0][4]['row']="10";
$z[0][4]['orderby']="rand";
$z[0][4]['titlelen']="45";
$z[0][4]['typeid']="all";
$z[1]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a></li>\r\n",954,1143);
$z[1][4]=array();
$z[1][4]['row']="10";
$z[1][4]['orderby']="pubdate";
$z[1][4]['titlelen']="45";
$z[1][4]['typeid']="all";
$z[2]=Array("tag"," \r\n  <a href=\"[field:link/]\" title=\"[field:tag /]\">[field:tag /]</a>\r\n  ",1245,1369);
$z[2][4]=array();
$z[2][4]['row']="30";
$z[2][4]['sort']="new";
$z[2][4]['getall']="1";

?>